export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

//LAYOUT
export const LAYOUT_SIDEBAR_OPEN = 'LAYOUT_SIDEBAR_OPEN';
export const LAYOUT_SIDEBAR_ICONS = 'LAYOUT_SIDEBAR_ICONS';
export const LAYOUT_SIDEBAR_CLOSED = 'LAYOUT_REGISTER_CLOSED';


// PROJECT
export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';
export const PROJECTS_ERROR = 'PROJECTS_ERROR';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_CREATED = 'PROJECTS_CREATED';
export const PROJECTS_CHANGED = 'PROJECTS_CHANGED';
export const PROJECTS_DELETED = 'PROJECTS_DELETED';

export const CURRENT_PROJECT = 'CURRENT_PROJECT';


// SPRINT
export const SPRINT_RECEIVED = 'SPRINT_RECEIVED';
export const SPRINT_ERROR = 'SPRINT_ERROR';
export const SPRINT_LOADING = 'SPRINT_LOADING';
export const SPRINT_CREATED = 'SPRINT_CREATED';
export const SPRINT_CHANGED = 'SPRINT_CHANGED';
export const SPRINT_DELETED = 'SPRINT_DELETED';


// TASK
export const TASK_RECEIVED = 'TASK_RECEIVED';
export const TASK_ERROR = 'TASK_ERROR';
export const TASK_LOADING = 'TASK_LOADING';
export const TASK_CREATED = 'TASK_CREATED';
export const TASK_CHANGED = 'TASK_CHANGED';
export const TASK_DELETED = 'TASK_DELETED';

